### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by alexhumanbean** [bencripps/react-redux-grid#140]
I have added react-redux-grid to my application and have error now (trying npm start).

Added to package.json dependencies:
"react-redux-grid": "^5.1.12" 
Added to my .tsx file:
        import { Grid } from 'react-redux-grid';
         ......
        \<Grid
          data={data}
          stateKey={stateKey}
        /\>

ERROR:
c:\work\spa\node_modules\react-redux-grid\dist\components\layout\header\Column.j
s:30
var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator
.vendor);
                             ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (c:\work\spa\node_modules\react-redux-grid\dist\compon
ents\layout\header\Column.js:30:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\work\spa\node_modules\react-redux-grid\dist\compon
ents\layout\Header.js:14:15)
    at Module._compile (module.js:570:32)

**Comment by bencripps** [comment]
What environment are you in? the `navigator` object is globally defined in all browsers I believe. Are you trying to render the browser in node?

**Comment by alexhumanbean** [comment]
I believe not. I see the error when I run "npm start" in console (windows command line)

**Comment by bencripps** [comment]
yeah you can't use this component in a node environment -- it's not an isomorphic component :(
