### ISSUE TITLE
Error trying to compile the library

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#39]
I tried to compile the library on the master branch by ```> npm run dist``` and I get the following error messages:
```
Error: src/components/Grid.jsx: Cannot find stylus file: ./../style/main.styl
    at Error (native)
    at compileStylusFile (D:\dev\github\react-redux-grid\node_modules\babel-plugin-stylus-compiler\build\index.js:48:11)
    at PluginPass.ImportDeclaration (D:\dev\github\react-redux-grid\node_modules\babel-plugin-stylus-compiler\build\index.js:72:21)
    at newFn (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\visitors.js:301:19)
    at NodePath._call (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\path\context.js:106:12)
    at TraversalContext.visitQueue (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\context.js:167:16)
    at TraversalContext.visitMultiple (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\context.js:113:17)
    at TraversalContext.visit (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\context.js:209:19)
    at Function.traverse.node (D:\dev\github\react-redux-grid\node_modules\babel-traverse\lib\index.js:161:17)
```

**Comment by bencripps** [comment]
So, I think this issue also stems from your trying to render the grid in a node environment. 

You do not need to run `npm dist` unless you're modifying core aspects of the grid (e.g. the header component, or stylus variables). 

All you will need to do is `npm install react-redux-grid` and import the grid into your client-side code, which does or does not need to be built via webpack (depending on what spec of JavaScript you're writing). The grid has already been built, and is browser compatible. 

Let me know if this helps!

**Comment by kayazinc** [comment]
Yes, I did the ```npm install react-redux-grid``` method and it works perfectly.
